# Generated by Django 6.0.6 on 2026-06-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='bank_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='cash_returned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
